---
title: "Thermodynamics in Prediction Markets"
author: "~sambex-fadsen"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Intuitively, it isn't all too surprising that there is a deep connection between prediction markets and thermodynamics given the logarithmic market scoring rule's relationship to information theory. However, to see the full extent of the connection we will need discuss an alternative way of running prediction markets...

## Automated Market Makers

Automated market makers (AMM's) are an elegant technology that exploit the duality between prices and probabilities to run prediction markets.

Given a disjoint partition of outcomes $\{1,2,...,N\}$ for some event, an AMM buys and sells securities corresponding to each outcome $i$ of the form "pays \$1 if $i$ occurs." Let $\vec{q}$ be the vector whose $i$th entry represents the number of shares of security $i$ held by the traders. Since the point of an AMM is to easily interpret prices as probabilities, we want security $i$'s price to increase if $q_i$ increases (the traders purchase some amount of security $i$) and decrease if $q_i$ decreases (the traders sell some amount of security $i$). However, this means that the price of a security must change for each infinitesimal amount of its shares that are bought or sold. Thus, prediction markets must use a 'cost function' $C$ to dictate how much an traders will have to pay for a specific transaction given the market's current state. For instance, if the market's participants currently hold $q_i$ of each security collectively and a trader wishes to now transact $r_i$ shares of each security, then this action would cost them:
$$C(\vec{q}+\vec{r})-C(\vec{q})$$
Note if we parameterize the path from $\vec{q}$ to $\vec{q}+\vec{r}$ by some function $a(t)$, then the price of security $i$ at each point along the transaction is given by:
$$p_i(a(t))=\frac{\partial C}{\partial a_i}$$
There are many different cost functions which can be used to run a prediction market, however the cost function:
$$C(\vec{q})=b\cdot \ln \sum_{i=1}^N e^{q_i/b}$$
is particularly nice since its prices are of the form:
$$p_i(\vec{q})=\frac{e^{q_i/b}}{\sum_{i=1}^N e^{q_i/b}}$$
, i.e. the Boltzmann distribution!

The Boltzmann AMM is equivalent to a LMSR since if the market's current probabilties are given by the above vector of prices and a trader wishes to change them to:
$$p_i(\vec{q}')=\frac{e^{q_i'/b}}{\sum_{i=1}^N e^{q_i'/b}}$$
then in case of event $i$ they will make:
\begin{align*}
(q_i'-q_i)-(C(\vec{q}')-C(\vec{q}))&=b \cdot \left(\frac{q_i'}{b}- \ln \sum_{i=1}^N e^{q_i'/b}\right)-b\cdot \left(\frac{q_i}{b}- \ln \sum_{i=1}^N e^{q_i/b}\right)
\\
&=b \cdot \ln\left(\frac{e^{q_i'/b}}{\sum_{i=1}^N e^{q_i'/b}}\right)-b \cdot \ln\left(\frac{e^{q_i}/b}{\sum_{i=1}^N e^{q_i/b}}\right)
\\
&=b \cdot \ln\left(\frac{p_i(\vec{q}')}{p_i(\vec{q})}\right)
\end{align*}

That is to say, their expected payoff is:
$$b \sum_{i=1}^N p_i(\vec{q}') \cdot \ln\left(\frac{p_i(\vec{q}')}{p_i(\vec{q})}\right)=b \cdot KL(p(\vec{q}') \ || \ p(\vec{q}))$$

## Jarzynski's Equality and The Second Law

Now that we have established the Boltzmann AMM is equivalent to a LMSR, it follows the maximum amount of money the market must pay out to its participants is:
$$b \cdot \ln(N)$$
which can be thought of as the subsidy the market uses for its own funding pool.

Additionally since:
$$C(\vec{0})=b\cdot \ln\left(\sum_{i=1}^N e^{0/b}\right)=b \cdot \ln(N)$$

and $C(\vec{q})-C(\vec{0})$ represents how much money agents must give the market for it to issue $\vec{q}$ of each security, the cost function of a Boltzmann AMM indicates how much money agents have given the market in the course of making bets in addition to the market's own funding pool. Therefore, the amount of money the market has given out at any point in time is:
$$F_{\text{AMM}}(\vec{q})=-(C(\vec{q})-b\cdot \ln(N))=-b \cdot \ln \frac{\sum_{i=1}^N e^{q_i/b}}{N}=-b\cdot \ln \langle e^{q_i/b} \rangle$$
This exactly parallels Jarzynski's equality and suggests we should start drawing some analogies! Note that if we interpret the amount of security $i$ held by the traders as the work performed by the AMM in state $i$, then $F_{\text{AMM}}$ (or the amount of money the market has given out) is identical to the equilibrium free energy in a thermodynamic process. This makes sense since the more money the market gives out, the more its capacity to perform work (have securities bought from it). 

This also allows us to immediately conclude that the money given out by the market at any given point in time is bounded above by the average number of shares sold to the market for each security $i$ since by Jensen's:
\begin{align*}
&\langle e^{q_i/b} \rangle \geq e^{\frac{\sum_{i=1}^N q_i/b}{N}}
\\
&\to \ln \langle e^{q_i/b} \rangle \geq \frac{\sum_{i=1}^N q_i/b}{N}
\\
&\to -b\cdot \ln \langle e^{q_i/b} \rangle \leq -\frac{\sum_{i=1}^N q_i}{N}
\\
&\to F_{\text{AMM}}(\vec{q}) \leq -\frac{\sum_{i=1}^N q_i}{N}
\end{align*}
, giving as a version of the second law of thermodynamics!

## The Second Law For Any Transaction

The above version of the second law only applies for a transaction in which there is intially $\vec{0}$ of each security issued.

In general, if the amount of each security sold changes from $\vec{q}$ to $\vec{q}'$ then the average work performed on the market (or the expected number of paying shares the market bought) is:
$$\overline{W}=\sum_{i=1}^N-(q'_i-q_i)\cdot p_i(\vec{q})=\sum_{i=1}^NW_i\cdot p_i(\vec{q})$$

and the change in free energy of our market (or the amount of money it gives out in the transaction) is:

\begin{align*}
\Delta F_{\text{AMM}}&=\left(-b\cdot \ln \langle e^{q_i/b} \rangle+(C(\vec{q})-C(\vec{q}'))\right)-\left(-b\cdot \ln \langle e^{q_i/b} \rangle\right)
\\
&=b \cdot \ln\left(\frac{\sum_{i=1}^N e^{q_i/b}}{\sum_{i=1}^N e^{q_i'/b}}\right)
\\
&=-b \cdot \ln\left(\sum_{i=1}^N e^{(q'_i-q_i)/b}\cdot \frac{e^{q_i/b}}{\sum_{j=1}^N e^{q_j/b}}\right)
\\
&=-b \cdot \ln\left(\sum_{i=1}^N e^{-W_i/b}\cdot p_i(\vec{q})\right)
\end{align*}

We wish to show:
$$\Delta F_{\text{AMM}} \leq \overline{W}$$
i.e., the amount of money given out by the market in a transaction is bounded above by the expected number of paying shares the market bought.

Note by Jensen's:
\begin{align*}
&\sum_{i=1}^N e^{-W_i/b}\cdot p_i(\vec{q}) \geq e^{\sum_{i=1}^N -\frac{W_i}{b} \cdot p_i(\vec{q})}
\\
& \to \ln\left(\sum_{i=1}^N e^{-W_i/b}\cdot p_i(\vec{q})\right) \geq \sum_{i=1}^N -\frac{W_i}{b} \cdot p_i(\vec{q})
\\ 
&\to -b \cdot \ln\left(\sum_{i=1}^N e^{-W_i/b}\cdot p_i(\vec{q})\right) \leq \sum_{i=1}^N W_i \cdot p_i(\vec{q})
\end{align*}
as desired.

Hence we have recovered the second law of thermodynamics for any arbitrary transaction that takes $\vec{q}$ to $\vec{q}'$!

## Thermodynamic Operations

We can also interpret the market's prices/probabilities at any given point in time as determining the energy landscape of our system.

If a trader's beliefs Pr$_{\text{trader}}$ disagrees with the current probability distribution given by the AMM's prices Pr$_{\text{AMM}}$ then according to their coarse graining the free energy is:
$$F_{\text{trader}}=-b\cdot \ln \langle e^{q_i/b} \rangle+b \cdot KL(\text{Pr}_{\text{trader}} \ || \ \text{Pr}_{\text{AMM}})$$
, i.e. they believe the market has given out $b \cdot KL(\text{Pr}_{\text{trader}} \ || \ \text{Pr}_{\text{AMM}})$ more dollars than the market believes. This strengthens our analogy since this expression is identical to that of the non-equilibrium free energy in a thermodynamic system.

If the trader carries out the appropriate transaction to adjust the market's prices to $\text{Pr}_{\text{trader}}$ (by changing the amount of each security sold from $\vec{q}$ to $\vec{q}'$), then
the AMM will believe the change in free energy is:
\begin{align*}
\Delta F_{\text{AMM}}&=\left(-b\cdot \ln \langle e^{q_i/b} \rangle+(C(\vec{q})-C(\vec{q}'))\right)-\left(-b\cdot \ln \langle e^{q_i/b} \rangle\right)
\\
&=b \cdot \ln\left(\frac{\sum_{i=1}^N e^{q_i/b}}{\sum_{i=1}^N e^{q_i'/b}}\right)
\end{align*}
and the trader will believe the change in free energy is:
\begin{align*}
\Delta F_{\text{trader}}&=\left(-b\cdot \ln \langle e^{q_i/b} \rangle+(C(\vec{q})-C(\vec{q}'))\right)-\left(-b\cdot \ln \langle e^{q_i/b} \rangle + b \cdot KL(\text{Pr}_{\text{trader}} \ || \ \text{Pr}_{\text{AMM}})\right)
\\
&=b \cdot \ln\left(\frac{\sum_{i=1}^N e^{q_i/b}}{\sum_{i=1}^N e^{q_i'/b}}\right)-b \cdot KL(\text{Pr}_{\text{trader}} \ || \ \text{Pr}_{\text{AMM}})
\end{align*}
This is nice because the first quantity tracks with the change in free energy for a system that starts and ends in equilibrium and the second quantity tracks with the change in free energy for a system that starts out of and ends in equilibrium. 

Moreover, we can interpret the discrepancy between the free energies as due to the 'arbitrage oppurtunity' arising from the system being out of equilibrium no longer existing for the trader and never having existed for the market. 

Alternatively, suppose our trader waits to adjust the market's prices to their beliefs and another participant comes along in the mean time and adjusts the market's prices to $\text{Pr}_{\text{participant}}$ (by changing the amount of each security sold from $\vec{q}$ to $\vec{q}'$). Then the trader will now believe the change in free energy is:
\begin{align*}
\Delta F_{\text{trader}}&=\left(-b\cdot \ln \langle e^{q_i/b} \rangle+(C(\vec{q})-C(\vec{q}')) + b \cdot KL(\text{Pr}_{\text{trader}} \ || \ \text{Pr}_{\text{participant}}) \right)-\left(-b\cdot \ln \langle e^{q_i/b} \rangle + b \cdot KL(\text{Pr}_{\text{trader}} \ || \ \text{Pr}_{\text{AMM}})\right)
\\
&=b \cdot \ln\left(\frac{\sum_{i=1}^N e^{q_i/b}}{\sum_{i=1}^N e^{q_i'/b}}\right)+\left(b \cdot KL(\text{Pr}_{\text{trader}} \ || \ \text{Pr}_{\text{participant}})-b \cdot KL(\text{Pr}_{\text{trader}} \ || \ \text{Pr}_{\text{AMM}})\right)
\end{align*}
which tracks with the change in free energy for a system that starts and ends out of equilibrium.


We can summarize the basic process underlying our prediction market as below:

\begin{align*}
&\to \text{[Initial market/landscape has certain amount of free energy corresponding to } \vec{q}\text{]}
\\
&\to \text{[Trader carries out transaction/performs work to profit from extra non-equilibrium free energy]}
\\
&\to \text{[Adjustment shifts market/landscape so that free energy corresponds to new }\vec{q}'\text{]}
\\
&\to \text{[Rinse and repeat]}
\end{align*}

